=== ahwagner/phenopacket-tools/phenopacket-tools-validator-jsonschema/src/main/resources/org/phenopackets/phenopackettools/validator/jsonschema/v2/phenopacket-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://www.ga4gh.org/phenopackets/phenopacket",
  "title": "Phenopacket",
  "description": "Schema for Global Alliance for Genomics and Health (GA4GH) Phenopacket",
  "type": "object",
  "required": ["id", "metaData"],
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "The unique identifier for the Phenopacket",
      "type": "string"
    },
    "subject": {
      "$ref": "#/definitions/individual"
    },
    "phenotypicFeatures": {
      "type": "array",
      "items": { "$ref": "#/definitions/phenotypicFeature" },
      "minItems": 1
    },
    "measurements": {
      "type": "array",
      "items": { "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/measurement.json#/definitions/measurement" },
      "minItems": 0
    },
    "biosamples": {
      "type": "array",
      "items": { "$ref": "#/definitions/biosample" },
      "minItems": 0
    },
    "interpretations": {
      "type": "array",
      "items": { "$ref": "#/definitions/interpretation" },
      "minItems": 0
    },
    "diseases": {
      "type": "array",
      "items": { "$ref": "#/definitions/disease" },
      "minItems": 0
    },
    "medicalActions": {
      "type": "array",
      "items": { "$ref": "#/definitions/medicalAction" },
      "minItems": 1
    },
    "files": {
      "type": "array",
      "items": { "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/file" },
      "minItems": 0
    },
    "metaData": {
      "$ref": "#/definitions/metaData" }
    },
    "definitions": {
    "update": {
      "type": "object",
      "properties": {
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "updatedBy": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      },
      "required": [
        "timestamp"
      ],
      "additionalProperties": false
    },
    "phenotypicFeature": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "excluded": {
          "type": "boolean"
        },
        "severity": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          }
        },
        "onset": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "resolution": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "evidence": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/evidence"
          },
          "minItems": 0
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": false
    },
    "variantInterpretation": {
      "type": "object",
      "properties": {
        "acmgPathogenicityClassification": {
          "enum": [
            "NOT_PROVIDED",
            "BENIGN",
            "LIKELY_BENIGN",
            "UNCERTAIN_SIGNIFICANCE",
            "LIKELY_PATHOGENIC",
            "PATHOGENIC"
          ]
        },
        "therapeuticActionability": {
          "enum": [
            "UNKNOWN_ACTIONABILITY",
            "NOT_ACTIONABLE",
            "ACTIONABLE"
          ]
        },
        "variationdescriptor": {
          "$ref" : "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/vrsatile.json#/definitions/variationDescriptor"

        }
      }
    },
    "geneDescriptor": {
      "type": "object",
      "properties": {
        "valueId": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "alternateIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "xrefs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "alternateSymbols": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "genomicInterpretation": {
      "type": "object",
      "properties": {
        "subjectOrBiosampleId": {
          "type": "string"
        },
        "interpretationStatus": {
          "enum": [
            "UNKNOWN_STATUS",
            "REJECTED",
            "CANDIDATE",
            "CONTRIBUTORY",
            "CAUSATIVE"
          ]
        },
        "variationInterpretation": {
          "oneOf": [
            {
              "$ref": "#/definitions/geneDescriptor"
            },
            {
              "$ref": "#/definitions/variantInterpretation"
            }
          ]
        }
      }
    },
    "individual": {
      "type": "object",
      "properties": {
        "id": {
          "description": "An arbitrary identifier for the subject of the Phenopacket",
          "type": "string"
        },
        "alternateIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date-time"
        },
        "timeAtLastEncounter": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "vitalStatus": {
          "type": "object",
          "properties": {
            "status": {
              "enum": ["UNKNOWN_STATUS", "ALIVE", "DECEASED"]
            },
            "timeOfDeath": {
              "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
            },
            "causeOfDeath": {
              "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
            },
            "survivalTimeInDays": {
              "type": "number"
            }
          }
        },
        "sex": {
          "$ref": "#/definitions/sex"
        },
        "karyotypicSex": {
          "enum": ["UNKNOWN_KARYOTYPE", "XX", "XY", "XO", "XXY","XXX","XXYY", "XXXY", "XXXX", "XYY", "OTHER_KARYOTYPE"]
        },
        "taxonomy": {"$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"}
        },
      "required": ["id"]
    },
    "sex": {
      "enum": ["UNKNOWN_SEX", "FEMALE", "MALE", "OTHER_SEX"]
    },
    "diagnosis": {
      "type": "object",
      "properties": {
        "disease": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "genomicInterpretations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/genomicInterpretation"
          }
        }
      },
      "required": [
        "disease"
      ]
    },
    "disease": {
      "type": "object",
      "properties": {
        "term": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "excluded": {
          "type": "boolean"
        },
        "onset": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "resolution": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "diseaseStage": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "clinicalTnmFinding": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          },
          "minItems": 0,
          "uniqueItems": true
        },
        "primarySite": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "laterality": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        }
      }
    },
    "interpretation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "progressStatus": {
          "enum": [
            "UNKNOWN_PROGRESS",
            "IN_PROGRESS",
            "COMPLETED",
            "SOLVED",
            "UNSOLVED"
          ]
        },
        "diagnosis": {
          "$ref": "#/definitions/diagnosis"
        },
        "summary" : {
          "type": "string"
        }
      },
      "required": [
        "id",
        "progressStatus"
      ]
    },
    "metaData": {
      "type": "object",
      "properties": {
        "created": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "submittedBy": {
          "type": "string"
        },
        "resources": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/resource"
          },
          "minItems": 1
        },
        "updates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/update"
          },
          "minItems": 1
        },
        "phenopacketSchemaVersion": { "enum": ["2.0"]},
        "externalReferences": {
          "type": "array",
          "items": { "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/externalReference" },
          "minItems": 0
        }
      },
      "required": ["created", "createdBy","phenopacketSchemaVersion"],
      "additionalProperties": false
    },
    "biosample": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "individualId": {
          "type": "string"
        },
        "derivedFromId": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "sampledTissue": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "sampledType": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "phenotypicFeatures": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/phenotypicFeature"
          }
        },
        "measurements": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/measurement.json#/definitions/measurement"
          }
        },
        "taxonomy": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "timeOfCollection": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "histologicalDiagnosis": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "tumorProgression": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "tumorGrade": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "pathologicalStage": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "pathologicalTnmFinding": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          }
        },
        "diagnosticMarkers": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          }
        },
        "procedure": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/procedure"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/file"
          }
        },
        "materialSample": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "sampleProcessing": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "sampleStorage": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "resource": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "namespacePrefix": {
          "type": "string"
        },
        "iriPrefix": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "url",
        "version",
        "namespacePrefix",
        "iriPrefix"
      ],
      "additionalProperties": false
    },
    "doseInterval": {
      "type": "object",
      "properties": {
        "quantity": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/measurement.json#/definitions/quantity"
        },
        "scheduleFrequency": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "interval": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeInterval"
        }
      },
      "required": [
        "quantity",
        "scheduleFrequency",
        "interval"
      ],
      "additionalProperties": false
    },
    "treatment": {
      "type": "object",
      "properties": {
        "agent": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "routeOfAdministration": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "doseIntervals": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/doseInterval"
          }
        },
        "drugType": {
          "enum": [
            "UNKNOWN_DRUG_TYPE",
            "PRESCRIPTION",
            "EHR_MEDICATION_LIST",
            "ADMINISTRATION_RELATED_TO_PROCEDURE"
          ]
        },
        "cumulativeDose": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/measurement.json#/definitions/quantity"
        }
      },
      "required": [
        "agent"
      ],
      "additionalProperties": false
    },
    "radiationTherapy": {
      "type": "object",
      "properties": {
        "modality": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "bodySite": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "dosage": {
          "type": "integer"
        },
        "fractions": {
          "type": "integer"
        }
      },
      "required": [
        "modality",
        "bodySite",
        "dosage",
        "fractions"
      ],
      "additionalProperties": false
    },
    "therapeuticRegimen": {
      "type": "object",
      "properties": {
        "ontologyClass": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "externalReference" : {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/externalReference"
        },
        "startTime": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "endTime": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/timeElement"
        },
        "regimenStatus": {
          "enum": [
            "UNKNOWN_STATUS",
            "STARTED",
            "COMPLETED",
            "DISCONTINUED"
          ]
        }
      },
      "oneOf": [
        { "required": [ "ontologyClass" ]},
        { "required": [ "externalReference" ]}
      ],
      "required": ["regimenStatus"],
      "additionalProperties": false
    },
    "medicalAction": {
      "type": "object",
      "properties": {
        "treatment": {
          "$ref": "#/definitions/treatment"
        },
        "procedure": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/procedure"
        },
        "radiationTherapy": {
          "$ref": "#/definitions/radiationTherapy"
        },
        "therapeuticRegimen": {
          "$ref": "#/definitions/therapeuticRegimen"
        },
        "treatmentTarget": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "treatmentIntent": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "responseToTreatment": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        },
        "adverseEvents": {
          "type": "array",
          "items": {
            "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
          }
        },
        "treatmentTerminationReason": {
          "$ref": "classpath:/org/phenopackets/phenopackettools/validator/jsonschema/v2/base.json#/definitions/ontologyClass"
        }
      },
      "additionalProperties": false,
      "oneOf": [ { "required": [ "procedure" ]},
        { "required": [ "radiationTherapy" ]},
        { "required": [ "therapeuticRegimen"]},
        { "required": [ "treatment" ]}
      ]
    }
  }
}

=== ahwagner/phenopacket-tools/phenopacket-tools-validator-jsonschema/src/test/resources/org/phenopackets/phenopackettools/validator/jsonschema/bethlem-myopathy.json
{
  "id": "arbitrary proband id",
  "subject": {
    "id": "proband A",
    "timeAtLastEncounter": {
      "age": {
        "iso8601duration": "P6Y3M"
      }
    },
    "sex": "MALE"
  },
  "phenotypicFeatures": [
    {
      "type": {
        "id": "HP:0001629",
        "label": "Ventricular septal defect"
      },
      "onset": {
        "gestationalAge": {
          "weeks": 23,
          "days": 4
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0001561",
        "label": "Polyhydramnios"
      },
      "onset": {
        "age": {
          "iso8601duration": "P7D"
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0000280",
        "label": "Coarse facial features"
      },
      "onset": {
        "ageRange": {
          "start": {
            "iso8601duration": "P14D"
          },
          "end": {
            "iso8601duration": "P21D"
          }
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0008689",
        "label": "Bilateral cryptorchidism"
      },
      "onset": {
        "ontologyClass": {
          "id": "HP:0003577",
          "label": "Congenital onset"
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0000054",
        "label": "Micropenis"
      },
      "onset": {
        "timestamp": "2000-01-23T01:23:45.123456789Z"
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0001798",
        "label": "Anonychia"
      },
      "onset": {
        "interval": {
          "start": "2000-01-23T01:23:45.123456789Z",
          "end": "2001-01-23T01:23:45.123456789Z"
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0001320",
        "label": "Cerebellar vermis hypoplasia"
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0000518",
        "label": "Cataract"
      },
      "onset": {
        "ontologyClass": {
          "id": "HP:0003593",
          "label": "Infantile onset"
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0002198",
        "label": "Dilated fourth ventricle"
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    },
    {
      "type": {
        "id": "HP:0100333",
        "label": "Unilateral cleft lip"
      },
      "onset": {
        "ontologyClass": {
          "id": "HP:0003577",
          "label": "Congenital onset"
        }
      },
      "evidence": [
        {
          "evidenceCode": {
            "id": "ECO:0000033",
            "label": "author statement supported by traceable reference"
          },
          "reference": {
            "id": "PMID:30808312",
            "description": "COL6A1 mutation leading to Bethlem myopathy with recurrent hematuria: a case report"
          }
        }
      ]
    }
  ],
  "measurements": [
    {
      "description": "Platelet measurement",
      "assay": {
        "id": "LOINC:26515-7",
        "label": "Platelets [#/volume] in Blood"
      },
      "value": {
        "quantity": {
          "unit": {
            "id": "UO:0000316",
            "label": "cells per microliter"
          },
          "value": 24000.0,
          "referenceRange": {
            "unit": {
              "id": "UO:0000316",
              "label": "cells per microliter"
            },
            "low": 150000.0,
            "high": 450000.0
          }
        }
      },
      "timeObserved": {
        "timestamp": "2020-10-01T10:54:20.123Z"
      },
      "procedure": {
        "code": {
          "id": "C173496",
          "label": "Peripheral Blood"
        },
        "performed": {
          "timestamp": "2020-09-29T10:54:20.012Z"
        }
      }
    },
    {
      "description": "Customized blood pressure measurement description.",
      "assay": {
        "id": "55417-0",
        "label": "Short blood pressure panel"
      },
      "complexValue": {
        "typedQuantities": [
          {
            "type": {
              "id": "NCIT:C25298",
              "label": "Systolic Blood Pressure"
            },
            "quantity": {
              "unit": {
                "id": "NCIT:C49670",
                "label": "Millimeter of Mercury"
              },
              "value": 165.0,
              "referenceRange": {
                "unit": {
                  "id": "NCIT:C49670",
                  "label": "Millimeter of Mercury"
                },
                "low": 110.0,
                "high": 125.0
              }
            }
          },
          {
            "type": {
              "id": "NCIT:C25299",
              "label": "Diastolic Blood Pressure"
            },
            "quantity": {
              "unit": {
                "id": "NCIT:C49670",
                "label": "Millimeter of Mercury"
              },
              "value": 105.0,
              "referenceRange": {
                "unit": {
                  "id": "NCIT:C49670",
                  "label": "Millimeter of Mercury"
                },
                "low": 70.0,
                "high": 80.0
              }
            }
          }
        ]
      },
      "timeObserved": {
        "timestamp": "2020-10-01T10:54:20.123Z"
      }
    }
  ],
  "interpretations": [
    {
      "id": "arbitrary interpretation id",
      "progressStatus": "COMPLETED",
      "diagnosis": {
        "disease": {
          "id": "OMIM:158810",
          "label": "Bethlem myopathy 1"
        },
        "genomicInterpretations": [
          {
            "subjectOrBiosampleId": "arbitrary interpretation id",
            "interpretationStatus": "CAUSATIVE",
            "variantInterpretation": {
              "acmgPathogenicityClassification": "PATHOGENIC",
              "variationDescriptor": {
                "id": "variant id",
                "expressions": [
                  {
                    "syntax": "hgvs",
                    "value": "NM_001848.2:c.877G\u003eA"
                  }
                ],
                "allelicState": {
                  "id": "GENO:0000135",
                  "label": "heterozygous"
                }
              }
            }
          }
        ]
      }
    }
  ],
  "files": [
    {
      "uri": "file://data/file.vcf.gz",
      "individualToFileIdentifiers": {
        "kindred 1A": "SAME000234"
      },
      "fileAttributes": {
        "genomeAssembly": "GRCh38",
        "fileFormat": "vcf"
      }
    }
  ],
  "metaData": {
    "created": "2021-05-14T10:35:00Z",
    "createdBy": "anonymous biocurator",
    "resources": [
      {
        "id": "hp",
        "name": "human phenotype ontology",
        "url": "http://purl.obolibrary.org/obo/hp.owl",
        "version": "2021-08-02",
